on: 
  pull_request:
    paths:
      - '**umpire_shroud.yaml'
      - '**genfumpiresplicer.f'

name: Generate C/FORTRAN Interface
jobs:
  generate-shroud:
    name: Run Shroud on changed files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Run shroud on changed files
        uses: ./.github/actions/shroud
      - name: Push changed files
        run: |
          printf "GitHub Actor: ${GITHUB_ACTOR}\n"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add src/umpire/interface/.
            git commit -m 'Update C/FORTRAN interface'
            git push
          fi
